### ISSUE TITLE
Basic ideas section of DSA

### ISSUE THREAD

**Issue by joehalloran** [ada-students/apprentice-handbook#18]
* **Year**: one
* **Subject**: data structures & algorithms
* **Chapter**: basic ideas
* **Section(s)**: 
  * [x] What is an algorithm
  * [x] How to write pseudo code

**Comment by rcsole** [comment]
What do you think of following the same structure as this one?

https://ada-students.gitbooks.io/apprentice-handbook/year-one/data-structures-and-algorithms/07-big-o-notation.html

Table of Contents + External resources.

**Comment by joehalloran** [comment]
Yep. I like it.
