### ISSUE TITLE
DSA Binary chapter

### ISSUE THREAD

**Issue by joehalloran** [ada-students/apprentice-handbook#50]
***Year**: one
* **Subject**: Data structure and algorithm
* **Chapter**: Binary
* **Section(s)**:
  * [ ] Highest possible value (i.e. n = 2 pow n -1)
  * [ ] Values of 2 pow n
  * [ ] Memory values (e.g. 1 MB in bytes)

**Comment by rcsole** [comment]
Closed by #55
