### ISSUE TITLE
Code on DSA chapter

### ISSUE THREAD

**Issue by rcsole** [ada-students/apprentice-handbook#9]
I think we should skip adding code on DSA. Exams and coursework are not supposed to test on actual code, rather how they work. By removing code we will make more room for definitions and it won't require you to actually know Java well enough to understand the code. We should eventually provide code samples, but not in the DSA section I think.

What do you think @QuinnStevens @shsulliv @joehalloran ?

**Comment by QuinnStevens** [comment]
Sounds good!

**Comment by rcsole** [comment]
I do believe there are occasions in which code would be useful, but Java would just get in the way. We could use pseudo-code for that. Thoughts?

**Comment by joehalloran** [comment]
Would short blocks of java code be useful? [For example](https://github.com/ada-students/apprentice-handbook/blob/joe-working-on-data-structures/book/year-one/data-structures-and-algorithms/05-data-structures.md#arrays-in-java).

**Comment by rcsole** [comment]
I think as long as they almost look like pseudo-code, they are fine. What I worry is code blocks that java `static`, `public`, methods in general. So long as they support the explanation I'm all in.

**Comment by joehalloran** [comment]
I think that is a good rule of thumb. Short code blocks only in DSA.
